name: testhoz
favicon: null
layout_spectrum: 0.1411743089556694
typography_spectrum: 0.45978274452500045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5596856013871729
  lightness: 0.10827852971851826
  saturation: 0.6901198483537883
  rhythmicContrast: 0.396571007091552
purpose: []
